"""Attach private blind-review answer keys before validating score rows."""
import argparse
import json
from pathlib import Path


def merge(scores: list[dict], answer_key: list[dict]) -> list[dict]:
    keyed = {row["review_id"]: row for row in answer_key}
    merged = []
    for score in scores:
        key = keyed.get(score.get("review_id"))
        if not key:
            raise ValueError("score references an unknown review_id")
        merged.append({**score, "case_id": key["case_id"], "variant": key["variant"]})
    return merged


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("scores", type=Path, help="Reviewer JSONL containing review_id and rubric scores")
    parser.add_argument("answer_key", type=Path, help="Private key generated by export_dayend_blind_review.py")
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    scores = [json.loads(line) for line in args.scores.read_text(encoding="utf-8").splitlines() if line.strip()]
    key = json.loads(args.answer_key.read_text(encoding="utf-8"))
    args.output.write_text("".join(json.dumps(row, ensure_ascii=False) + "\n" for row in merge(scores, key)), encoding="utf-8")


if __name__ == "__main__": main()
