import { FormEvent, useEffect, useState } from 'react';
import { BookOpen, BrainCircuit, Lightbulb, Send, UserCheck } from 'lucide-react';
import { api } from '../../api/client';
import { MarkdownViewer } from '../../components/MarkdownViewer';
import { useAppStore } from '../../stores/useAppStore';
import type { ChatMessage } from '../../types';

const modes = [{ id: 'detail', name: '详细讲解', icon: BookOpen }, { id: 'quick', name: '快速复习', icon: Lightbulb }, { id: 'socratic', name: '苏格拉底', icon: BrainCircuit }, { id: 'exam', name: '考官模式', icon: UserCheck }];
export default function AIStudyRoom() {
  const subject = useAppStore((s) => s.currentSubject)!;
  const [messages, setMessages] = useState<ChatMessage[]>([]); const [mode, setMode] = useState('detail'); const [sending, setSending] = useState(false); const [error, setError] = useState('');
  useEffect(() => { api.chatHistory(subject.id).then(setMessages).catch((e) => setError(e.message)); }, [subject.id]);
  async function send(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const input = form.elements.namedItem('message') as HTMLTextAreaElement; const content = input.value.trim(); if (!content) return; setMessages((rows) => [...rows, { id: crypto.randomUUID(), role: 'user', content, createdAt: new Date().toISOString() }]); input.value = ''; setSending(true); try { const reply = await api.chat({ subject_id: subject.id, content, mode }); setMessages((rows) => [...rows, reply]); } catch (e) { setError(e instanceof Error ? e.message : '发送失败'); } finally { setSending(false); } }
  return <div className="flex h-full bg-white"><aside className="hidden w-60 shrink-0 border-r bg-slate-50 p-4 lg:block"><h2 className="mb-4 font-bold">学习模式</h2><div className="space-y-2">{modes.map(({ id, name, icon: Icon }) => <button key={id} onClick={() => setMode(id)} className={`flex w-full items-center rounded-xl p-3 text-left text-sm ${mode === id ? 'border border-blue-200 bg-blue-50 font-semibold text-blue-700' : 'text-slate-600 hover:bg-slate-100'}`}><Icon size={17} className="mr-2"/>{name}</button>)}</div></aside><section className="flex min-w-0 flex-1 flex-col"><header className="border-b px-6 py-4 font-bold">{subject.name} · AI 学习室</header><div className="flex-1 space-y-6 overflow-y-auto p-5 md:p-8">{messages.map((message) => <div key={message.id} className={`flex ${message.role === 'user' ? 'justify-end' : ''}`}><div className={`max-w-3xl rounded-2xl p-4 ${message.role === 'user' ? 'bg-blue-600 text-white' : 'border border-slate-100 bg-slate-50'}`}><MarkdownViewer content={message.content}/>{message.citations?.map((citation) => <div key={citation.id} className="mt-3 rounded-lg border bg-white p-3 text-xs text-slate-600">[{citation.sourceName} P{citation.page}] {citation.text}</div>)}</div></div>)}{sending && <div className="text-sm text-slate-400">AI 正在组织回答…</div>}{error && <div className="text-rose-600">{error}</div>}</div><form onSubmit={send} className="border-t p-4"><div className="relative mx-auto max-w-4xl"><textarea name="message" rows={3} placeholder={`向 AI 提问关于 ${subject.name} 的问题…`} className="w-full resize-none rounded-2xl border border-slate-200 bg-slate-50 p-4 pr-14 outline-none focus:border-blue-400"/><button disabled={sending} className="absolute bottom-3 right-3 rounded-xl bg-blue-600 p-2 text-white"><Send size={18}/></button></div></form></section></div>;
}
